### ISSUE TITLE
AttributeError: module 'torchmcubes_module' has no attribute 'mcubes_cuda'

### ISSUE THREAD

**Issue by CAOXINGWEN** [myavartanoo/3DIAS_PyTorch#2]
Hey, thank you for your excellent work. I encountered a problem while running the demo. py file. Can you help me take a look

pythone demo.py --device "0" --inputimg "./input/2.png" --config "./weights/single/chair/config.json" --resume "./weights/single/chair/checkpoint-epoch546.pth"
load model
Traceback (most recent call last):
  File "demo.py", line 77, in <module>
    main(config)
  File "demo.py", line 36, in main
    meshlist, total_mesh, _ = generate_mesh(polycoeff, A_10x10)
  File "/media/caoxingwen/work/3DIAS/utils/generate_figure.py", line 36, in generate_mesh
    verts0, faces0 = marching_cubes(func_val, 0.0)
  File "/home/caoxingwen/anaconda3/envs/3dais/lib/python3.8/site-packages/torchmcubes/__init__.py", line 12, in marching_cubes
    return mc.mcubes_cuda(vol, thresh)
AttributeError: module 'torchmcubes_module' has no attribute 'mcubes_cuda'

**Comment by robot0321** [comment]
Hi, 
`torchmcubes` library has two different versions: `pip` version and `git repo` verison.
We used git repository version which supports cuda calculation
As noticed in `README.md`, see [here](https://github.com/tatsy/torchmcubes)
